version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver

    flower:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        command: scheduler

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        command: worker
