version: '2'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - POSTGRES_DB=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        volumes:
            - ./dags:/usr/local/airflow/dags
        ports:
            - "8080:8080"
        command: webserver